import { randomUUID } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';

test('mirror slice4 draft authoring, scope, replay, ordered sessions and reload', async ({ page }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8001', 'Isolated synthetic E2E only');
  const number = String(20000000 + Math.floor(Math.random() * 60000000));
  let sum = 0;
  for (let i = 0; i < number.length; i++) sum += Number(number[number.length - 1 - i]) * (2 + i % 6);
  const check = 11 - sum % 11;
  const response = await page.request.post('/api/patients', { data: { first_name: 'Sintética', last_name: `Planes ${randomUUID().slice(0, 8)}`, rut: `${number}-${check === 11 ? '0' : check === 10 ? 'K' : check}` } });
  expect(response.status()).toBe(201);
  const patientId = (await response.json()).id;
  const base = `/api/patients/${patientId}/clinical-plans`;
  await page.goto(`/patients/${patientId}?tab=clinical&clinical=planning`);
  await expect(page.getByText('Cargando planes', { exact: true })).toBeHidden();
  await page.getByLabel('Título del plan', { exact: true }).fill('Plan sintético');
  await page.getByRole('button', { name: 'Crear borrador', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plan sintético', exact: true })).toBeVisible();
  const composer = page.getByRole('form', { name: 'Procedimiento planificado', exact: true });
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('button', { name: /^Pieza 16:/ }).click();
  await composer.getByRole('textbox', { name: 'Sesiones (una por línea)', exact: true }).fill('Preparación\nColocación');
  await page.getByRole('button', { name: 'Diagnóstico', exact: true }).click();
  const guard = page.getByRole('dialog', { name: 'Cambios sin guardar', exact: true });
  await expect(guard).toBeVisible();
  await guard.getByRole('button', { name: 'Permanecer', exact: true }).click();
  let original: unknown;
  await page.route('**/clinical-plans/*/items', async route => {
    original = route.request().postDataJSON();
    await route.fetch(); await route.abort();
  }, { times: 1 });
  await composer.getByRole('button', { name: 'Añadir procedimiento', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reintentar misma operación', exact: true })).toBeVisible();
  const retry = page.waitForRequest(request => request.method() === 'POST' && request.url().endsWith('/items'));
  await page.getByRole('button', { name: 'Reintentar misma operación', exact: true }).click();
  expect((await retry).postDataJSON()).toEqual(original);
  await expect(page.getByText('1. Bracket individual (reposición)', { exact: true })).toBeVisible();
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('REST-BRIDGE-ZIR');
  for (const tooth of [14, 15, 16]) await composer.getByRole('button', { name: new RegExp(`^Pieza ${tooth}:`) }).click();
  await composer.getByRole('group', { name: 'Pieza 15', exact: true }).getByRole('combobox', { name: 'Rol', exact: true }).selectOption('pontic');
  await composer.getByRole('button', { name: 'Añadir procedimiento', exact: true }).click();
  await expect(page.getByText('2. Puente zirconio', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Subir procedimiento 2', exact: true }).click();
  await expect(page.getByText('1. Puente zirconio', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Editar sesión 1', exact: true }).last().click();
  await page.getByRole('textbox', { name: 'Nombre de sesión', exact: true }).fill('Preparación revisada');
  await page.getByRole('button', { name: 'Guardar sesión', exact: true }).click();
  await expect(page.getByText('1. Preparación revisada · Pendiente', { exact: true })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('slice4-draft-desktop.png') });
  const plans = (await (await page.request.get(base)).json()).items;
  expect(plans).toHaveLength(1);
  expect(plans[0].items.map((item: { treatment: { variant_id: string } }) => item.treatment.variant_id)).toEqual(['REST-BRIDGE-ZIR', 'ORTO-BRACK']);
  expect((await (await page.request.get(`/api/patients/${patientId}/dental-treatments`)).json()).total).toBe(0);
  await page.reload();
  await page.getByRole('button', { name: 'Plan sintético · Borrador', exact: true }).click();
  await expect(page.getByText('1. Puente zirconio', { exact: true })).toBeVisible();
  await expect(page.getByText('1. Preparación revisada · Pendiente', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const closeNavigation = page.getByRole('button', { name: 'Cerrar navegación', exact: true });
  if (await closeNavigation.isVisible()) await closeNavigation.click();
  await expect.poll(() => page.locator('.sidebar-container').evaluate((node) => node.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await page.getByText('1. Puente zirconio', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath('slice4-draft-narrow.png') });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('button', { name: /^Seleccionar pieza 17:/ }).click();
  await page.getByRole('tab', { name: 'Información', exact: true }).click();
  await guard.getByRole('button', { name: 'Guardar y continuar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Notas generales', exact: true })).toBeVisible();
  const savedOnLeave = (await (await page.request.get(`${base}/${plans[0].id}`)).json());
  expect(savedOnLeave.items).toHaveLength(3);
  expect(savedOnLeave.items[2].treatment.teeth[0].tooth_fdi).toBe(17);
  await test.info().attach('slice4-persisted', { body: JSON.stringify({ patientId, plan: plans[0] }), contentType: 'application/json' });
});

test('mirror slice5 explicit confirmation, acceptance, closure, reactivation and history', async ({ page }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8001', 'Isolated synthetic E2E only');
  const number = String(20000000 + Math.floor(Math.random() * 60000000));
  let sum = 0;
  for (let i = 0; i < number.length; i++) sum += Number(number[number.length - 1 - i]) * (2 + i % 6);
  const check = 11 - sum % 11;
  const response = await page.request.post('/api/patients', { data: { first_name: 'Sintética', last_name: `Ciclo ${randomUUID().slice(0, 8)}`, rut: `${number}-${check === 11 ? '0' : check === 10 ? 'K' : check}` } });
  expect(response.status()).toBe(201);
  const patientId = (await response.json()).id;
  const base = `/api/patients/${patientId}/clinical-plans`;
  await page.goto(`/patients/${patientId}?tab=clinical&clinical=planning`);
  await page.getByRole('textbox', { name: 'Título del plan', exact: true }).fill('Ciclo clínico sintético');
  await page.getByRole('button', { name: 'Crear borrador', exact: true }).click();
  const composer = page.getByRole('form', { name: 'Procedimiento planificado', exact: true });
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('button', { name: /^Pieza 16:/ }).click();
  await composer.getByRole('button', { name: 'Añadir procedimiento', exact: true }).click();
  await expect(page.getByText('Borrador · Revisión 2', { exact: true })).toBeVisible();
  const confirmAction = async (label: string): Promise<void> => {
    await page.getByRole('button', { name: label, exact: true }).click();
    await page.getByRole('dialog', { name: label, exact: true }).getByRole('button', { name: label, exact: true }).click();
  };
  await confirmAction('Confirmar plan');
  await expect(page.getByText('Pendiente de aceptación · Revisión 3', { exact: true })).toBeVisible();
  await confirmAction('Reabrir plan');
  await expect(page.getByText('Borrador · Revisión 4', { exact: true })).toBeVisible();
  await confirmAction('Confirmar plan');
  await page.getByRole('button', { name: 'Registrar aceptación', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nota de aceptación (opcional)', exact: true }).fill('Aceptación clínica sintética');
  await page.getByRole('button', { name: 'Revisar acción', exact: true }).click();
  const acceptance = page.getByRole('dialog', { name: 'Registrar aceptación', exact: true });
  await expect(acceptance.getByText(/No representa una firma/)).toBeVisible();
  let original: unknown;
  await page.route('**/clinical-plans/*/accept', async route => { original = route.request().postDataJSON(); await route.fetch(); await route.abort(); }, { times: 1 });
  await acceptance.getByRole('button', { name: 'Registrar aceptación', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reintentar misma operación', exact: true })).toBeVisible();
  const retry = page.waitForRequest(request => request.method() === 'POST' && request.url().endsWith('/accept'));
  await page.getByRole('button', { name: 'Reintentar misma operación', exact: true }).click();
  expect((await retry).postDataJSON()).toEqual(original);
  await expect(page.getByText('En curso · Revisión 6', { exact: true })).toBeVisible();
  await expect(page.getByText(/Aceptación registrada/)).toContainText('Aceptación clínica sintética');
  await page.screenshot({ path: test.info().outputPath('slice5-accepted-desktop.png') });
  await page.getByRole('button', { name: 'Cerrar plan', exact: true }).click();
  await page.getByRole('combobox', { name: 'Motivo del cierre', exact: true }).selectOption('expired');
  await page.getByRole('textbox', { name: 'Nota del cierre (opcional)', exact: true }).fill('Cierre sintético');
  await page.getByRole('button', { name: 'Revisar acción', exact: true }).click();
  await page.getByRole('dialog', { name: 'Cerrar plan', exact: true }).getByRole('button', { name: 'Cerrar plan', exact: true }).click();
  await expect(page.getByText('Cerrado · Revisión 7', { exact: true })).toBeVisible();
  await expect(page.getByText('Plan de solo lectura. Su historial se conserva.', { exact: true })).toBeVisible();
  await expect(composer).toBeHidden();
  const closed = (await (await page.request.get(base)).json()).items[0];
  expect(closed.closure_reason).toBe('expired');
  expect(closed.accepted_at).toBeTruthy();
  const denied = await page.request.patch(`${base}/${closed.id}`, { data: { operation_id: randomUUID(), expected_revision: 7, title: 'Forbidden' } });
  expect(denied.status()).toBe(409);
  await page.reload();
  await page.getByRole('button', { name: 'Ciclo clínico sintético · Cerrado', exact: true }).click();
  await expect(page.getByText('Cerrado · Revisión 7', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const closeNavigation = page.getByRole('button', { name: 'Cerrar navegación', exact: true });
  if (await closeNavigation.isVisible()) await closeNavigation.click();
  await expect.poll(() => page.locator('.sidebar-container').evaluate((node) => node.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await page.getByRole('button', { name: 'Reactivar plan', exact: true }).click();
  const reactivation = page.getByRole('dialog', { name: 'Reactivar plan', exact: true });
  await page.screenshot({ path: test.info().outputPath('slice5-reactivation-narrow.png') });
  await reactivation.getByRole('button', { name: 'Reactivar plan', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByText('Borrador · Revisión 8', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Historial del plan', exact: true }).click();
  await expect(page.getByText(/Revisión 7 · Cerrar plan/)).toBeVisible();
  const history = (await (await page.request.get(`${base}/${closed.id}/revisions`)).json()).items;
  expect(history.find((revision: { revision: number }) => revision.revision === 7).after.closure_reason).toBe('expired');
  expect(history.find((revision: { revision: number }) => revision.revision === 6).after.acceptance_note).toBe('Aceptación clínica sintética');
  await test.info().attach('slice5-persisted', { body: JSON.stringify({ patientId, planId: closed.id, closedRevision: closed.revision, history }), contentType: 'application/json' });
});

test('mirror slice6 staged execution, atomic note replay, conflict and retained correction evidence', async ({ page, context }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8001', 'Isolated synthetic E2E only');
  const number = String(20000000 + Math.floor(Math.random() * 60000000));
  let sum = 0;
  for (let i = 0; i < number.length; i++) sum += Number(number[number.length - 1 - i]) * (2 + i % 6);
  const check = 11 - sum % 11;
  const response = await page.request.post('/api/patients', { data: { first_name: 'Sintética', last_name: `Ejecución ${randomUUID().slice(0, 8)}`, rut: `${number}-${check === 11 ? '0' : check === 10 ? 'K' : check}` } });
  expect(response.status()).toBe(201);
  const patientId = (await response.json()).id;
  const base = `/api/patients/${patientId}/clinical-plans`;
  const route = `/patients/${patientId}?tab=clinical&clinical=planning`;
  await page.goto(route);
  await page.getByRole('textbox', { name: 'Título del plan', exact: true }).fill('Ejecución sintética');
  await page.getByRole('button', { name: 'Crear borrador', exact: true }).click();
  const composer = page.getByRole('form', { name: 'Procedimiento planificado', exact: true });
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('button', { name: /^Pieza 16:/ }).click();
  await composer.getByRole('textbox', { name: 'Sesiones (una por línea)', exact: true }).fill('Preparación\nColocación');
  await composer.getByRole('button', { name: 'Añadir procedimiento', exact: true }).click();
  await expect(page.getByText('Borrador · Revisión 2', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Confirmar plan', exact: true }).click();
  await page.getByRole('dialog', { name: 'Confirmar plan', exact: true }).getByRole('button', { name: 'Confirmar plan', exact: true }).click();
  await page.getByRole('button', { name: 'Registrar aceptación', exact: true }).click();
  await page.getByRole('button', { name: 'Revisar acción', exact: true }).click();
  await page.getByRole('dialog', { name: 'Registrar aceptación', exact: true }).getByRole('button', { name: 'Registrar aceptación', exact: true }).click();
  await expect(page.getByText('En curso · Revisión 4', { exact: true })).toBeVisible();
  const other = await context.newPage();
  await other.goto(route);
  await other.getByRole('button', { name: 'Ejecución sintética · En curso', exact: true }).click();
  await expect(other.getByText('En curso · Revisión 4', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Completar siguiente sesión', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nota clínica del procedimiento (opcional)', exact: true }).fill('Evidencia sintética de preparación');
  await page.getByRole('tab', { name: 'Información', exact: true }).click();
  const guard = page.getByRole('dialog', { name: 'Cambios sin guardar', exact: true });
  await expect(guard.getByRole('button', { name: 'Guardar y continuar', exact: true })).toBeHidden();
  await guard.getByRole('button', { name: 'Permanecer', exact: true }).click();
  await page.getByRole('button', { name: 'Revisar ejecución', exact: true }).click();
  let original: unknown;
  await page.route('**/stages/*/complete', async intercepted => { original = intercepted.request().postDataJSON(); await intercepted.fetch(); await intercepted.abort(); }, { times: 1 });
  await page.getByRole('dialog', { name: 'Completar sesión', exact: true }).getByRole('button', { name: 'Completar sesión', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reintentar misma operación', exact: true })).toBeVisible();
  const retry = page.waitForRequest(request => request.method() === 'POST' && request.url().endsWith('/complete'));
  await page.getByRole('button', { name: 'Reintentar misma operación', exact: true }).click();
  expect((await retry).postDataJSON()).toEqual(original);
  await expect(page.getByText('1/2 sesiones completadas', { exact: true })).toBeVisible();
  await expect(page.getByText('Evidencia sintética de preparación', { exact: true })).toBeVisible();
  await expect(page.getByText('0/1 procedimientos completados', { exact: true })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('slice6-partial-desktop.png') });
  await other.getByRole('button', { name: 'Cancelar sesión 2', exact: true }).click();
  await other.getByRole('textbox', { name: 'Motivo de cancelación (opcional)', exact: true }).fill('Texto de otra sesión');
  await other.getByRole('button', { name: 'Revisar ejecución', exact: true }).click();
  await other.getByRole('dialog', { name: 'Cancelar sesión', exact: true }).getByRole('button', { name: 'Cancelar sesión', exact: true }).click();
  await other.getByRole('button', { name: 'Revisar versión guardada', exact: true }).click();
  await expect(other.getByText('En curso · Revisión 5', { exact: true })).toBeVisible();
  await expect(other.getByRole('textbox', { name: 'Motivo de cancelación (opcional)', exact: true })).toHaveValue('Texto de otra sesión');
  await other.getByRole('button', { name: 'Revisar ejecución', exact: true }).click();
  await other.getByRole('dialog', { name: 'Cancelar sesión', exact: true }).getByRole('button', { name: 'Cancelar sesión', exact: true }).click();
  await expect(other.getByText('Completado · Revisión 6', { exact: true })).toBeVisible();
  const completed = (await (await page.request.get(base)).json()).items[0];
  expect(completed.items[0].treatment.state).toBe('performed');
  expect(completed.items[0].stages.map((stage: { status: string }) => stage.status)).toEqual(['completed', 'cancelled']);
  await other.close();
  await page.reload();
  await page.getByRole('button', { name: 'Ejecución sintética · Completado', exact: true }).click();
  await expect(page.getByText('Evidencia sintética de preparación', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Corregir registro del procedimiento', exact: true }).click();
  await page.getByRole('textbox', { name: 'Motivo de corrección', exact: true }).fill('Corrección sintética');
  await page.getByRole('button', { name: 'Revisar corrección', exact: true }).click();
  await page.getByRole('dialog', { name: 'Corregir registro del procedimiento', exact: true }).getByRole('button', { name: 'Marcar como erróneo', exact: true }).click();
  await expect(page.getByText('Completado · Revisión 7', { exact: true })).toBeVisible();
  await expect(page.getByText(/Registro marcado como erróneo/)).toBeVisible();
  await expect(page.getByRole('button', { name: 'Reabrir plan', exact: true })).toBeHidden();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const closeNavigation = page.getByRole('button', { name: 'Cerrar navegación', exact: true });
  if (await closeNavigation.isVisible()) await closeNavigation.click();
  await expect.poll(() => page.locator('.sidebar-container').evaluate((node) => node.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await page.getByRole('button', { name: 'Historial del plan', exact: true }).click();
  await expect(page.getByText(/Revisión 7 · Corregir procedimiento/)).toBeVisible();
  await page.getByText('1/2 sesiones completadas', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath('slice6-corrected-narrow.png') });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const persisted = (await (await page.request.get(`${base}/${completed.id}`)).json());
  expect(persisted.items[0].stages).toEqual(completed.items[0].stages);
  const evidencePath = test.info().outputPath('slice6-persisted.json');
  await writeFile(evidencePath, JSON.stringify({ patientId, completed, persisted }, null, 2));
  await test.info().attach('slice6-persisted', { path: evidencePath, contentType: 'application/json' });
});

test('mirror slice6 all cancellation stays truthful and reactivation retains partial work', async ({ page }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8001', 'Isolated synthetic E2E only');
  const number = String(20000000 + Math.floor(Math.random() * 60000000));
  let sum = 0;
  for (let i = 0; i < number.length; i++) sum += Number(number[number.length - 1 - i]) * (2 + i % 6);
  const check = 11 - sum % 11;
  const response = await page.request.post('/api/patients', { data: { first_name: 'Sintética', last_name: `Sesiones ${randomUUID().slice(0, 8)}`, rut: `${number}-${check === 11 ? '0' : check === 10 ? 'K' : check}` } });
  expect(response.status()).toBe(201);
  const patientId = (await response.json()).id;
  const base = `/api/patients/${patientId}/clinical-plans`;
  const plans: { id: string; title: string }[] = [];
  for (const title of ['Cancelación total', 'Trabajo parcial']) {
    const id = randomUUID();
    expect((await page.request.post(base, { data: { id, operation_id: randomUUID(), expected_revision: 0, title } })).status()).toBe(201);
    const path = `${base}/${id}`;
    expect((await page.request.post(`${path}/items`, { data: { id: randomUUID(), operation_id: randomUUID(), expected_revision: 1,
      treatment: { id: randomUUID(), variant_id: 'ORTO-BRACK', dentition: 'permanent', teeth: [{ tooth_fdi: 16 }] },
      stages: [{ label: 'Primera' }, { label: 'Segunda' }] } })).status()).toBe(201);
    expect((await page.request.post(`${path}/confirm`, { data: { operation_id: randomUUID(), expected_revision: 2 } })).status()).toBe(200);
    expect((await page.request.post(`${path}/accept`, { data: { operation_id: randomUUID(), expected_revision: 3 } })).status()).toBe(200);
    plans.push({ id, title });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto(`/patients/${patientId}?tab=clinical&clinical=plans`);
  await page.getByRole('button', { name: 'Cancelación total · En curso', exact: true }).click();
  for (const sequence of [1, 2]) {
    await page.getByRole('button', { name: `Cancelar sesión ${sequence}`, exact: true }).click();
    await page.getByRole('button', { name: 'Revisar ejecución', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Cancelar sesión', exact: true });
    await dialog.getByRole('button', { name: 'Cancelar sesión', exact: true }).focus();
    await page.keyboard.press('Enter');
    await expect(page.getByText(`En curso · Revisión ${4 + sequence}`, { exact: true })).toBeVisible();
  }
  await expect(page.getByText('0/2 sesiones completadas', { exact: true })).toBeVisible();
  await expect(page.getByText('0/1 procedimientos completados', { exact: true })).toBeVisible();
  await expect(page.getByText(/cancelados siguen en el total/)).toBeVisible();
  const cancelled = (await (await page.request.get(`${base}/${plans[0].id}`)).json());
  expect(cancelled.state).toBe('active');
  expect(cancelled.items[0].treatment.state).toBe('cancelled');
  await page.getByText('0/2 sesiones completadas', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath('slice6-cancelled-narrow.png') });
  await page.getByRole('button', { name: 'Volver a planes', exact: true }).click();
  await page.getByRole('button', { name: 'Trabajo parcial · En curso', exact: true }).click();
  await page.getByRole('button', { name: 'Completar siguiente sesión', exact: true }).click();
  await page.getByRole('button', { name: 'Revisar ejecución', exact: true }).click();
  await page.getByRole('dialog', { name: 'Completar sesión', exact: true }).getByRole('button', { name: 'Completar sesión', exact: true }).click();
  await expect(page.getByText('1/2 sesiones completadas', { exact: true })).toBeVisible();
  const partial = (await (await page.request.get(`${base}/${plans[1].id}`)).json());
  await page.getByRole('button', { name: 'Cerrar plan', exact: true }).click();
  await page.getByRole('combobox', { name: 'Motivo del cierre', exact: true }).selectOption('patient_abandoned');
  await page.getByRole('button', { name: 'Revisar acción', exact: true }).click();
  await page.getByRole('dialog', { name: 'Cerrar plan', exact: true }).getByRole('button', { name: 'Cerrar plan', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Trabajo parcial · Cerrado', exact: true }).click();
  await page.getByRole('button', { name: 'Reactivar plan', exact: true }).click();
  await page.getByRole('dialog', { name: 'Reactivar plan', exact: true }).getByRole('button', { name: 'Reactivar plan', exact: true }).click();
  await expect(page.getByText('Borrador · Revisión 7', { exact: true })).toBeVisible();
  await expect(page.getByText('1/2 sesiones completadas', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Editar sesión 1', exact: true })).toBeHidden();
  expect((await (await page.request.get(`${base}/${plans[1].id}`)).json()).items).toEqual(partial.items);
  const evidencePath = test.info().outputPath('slice6-cancellation-reactivation.json');
  await writeFile(evidencePath, JSON.stringify({ patientId, cancelled, partial }, null, 2));
  await test.info().attach('slice6-cancellation-reactivation', { path: evidencePath, contentType: 'application/json' });
});
