import { randomUUID } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { type Page, expect, test } from '@playwright/test';

const evidencePrefix = process.env.E2E_EVIDENCE_PREFIX ?? 'slice8';

function syntheticRut(): string {
  const body = String(20000000 + Math.floor(Math.random() * 60000000));
  let sum = 0;
  for (let i = 0; i < body.length; i++) sum += Number(body[body.length - 1 - i]) * (2 + i % 6);
  const check = 11 - sum % 11;
  return `${body}-${check === 11 ? '0' : check === 10 ? 'K' : check}`;
}

test.use({ storageState: { cookies: [], origins: [] }, actionTimeout: 15000 });
test('mirror slice8 diagnosis to selected plan, two sessions, history and guarded patient switch', async ({ page, context, playwright }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8018', 'Owned disposable Docker proof only');
  const credentials = { email: process.env.E2E_PROOF_USER ?? `journey-${randomUUID()}@example.com`, password: process.env.E2E_PROOF_PASSWORD ?? randomUUID() };
  const login = await page.request.post('/api/auth/login', { data: credentials });
  if (login.status() === 401) expect((await page.request.post('/api/auth/signup', { data: credentials })).status()).toBe(201);
  else expect(login.ok()).toBeTruthy();
  const createPatient = async (label: string): Promise<string> => {
    const response = await page.request.post('/api/patients', { data: { first_name: 'Sintética', last_name: label, rut: syntheticRut() } });
    expect(response.status()).toBe(201);
    return (await response.json()).id;
  };
  const patientLabel = `Journey ${randomUUID().slice(0, 8)}`;
  const patientId = await createPatient(patientLabel);
  const secondId = await createPatient(`Otro ${randomUUID().slice(0, 8)}`);
  const base = `/api/patients/${patientId}`;
  const diagnosis = `/patients/${patientId}?tab=clinical&clinical=diagnosis`;
  const command = (revision: number, extra = {}) => ({ operation_id: randomUUID(), expected_revision: revision, ...extra });
  const unusedId = randomUUID();
  expect((await page.request.post(`${base}/clinical-plans`, { data: command(0, { id: unusedId, title: 'Otro borrador' }) })).status()).toBe(201);
  await page.goto(diagnosis);
  await expect(page.getByRole('heading', { name: 'Odontograma FDI' })).toBeVisible();
  await page.getByRole('button', { name: 'Pulpitis', exact: true }).click();
  await page.getByRole('button', { name: /^Pieza 16:/ }).click();
  await expect.poll(async () => (await (await page.request.get(`${base}/conditions`)).json()).total).toBe(1);
  const finding = (await (await page.request.get(`${base}/conditions`)).json()).items[0];
  await page.getByRole('button', { name: /Ortodoncia/, exact: false }).click();
  await page.getByRole('button', { name: 'Bracket individual (reposición)', exact: true }).click();
  await page.getByRole('button', { name: /^Pieza 17:/ }).click();
  await expect.poll(async () => (await (await page.request.get(`${base}/dental-treatments`)).json()).total).toBe(1);
  const observed = (await (await page.request.get(`${base}/dental-treatments`)).json()).items[0];
  await page.getByRole('button', { name: 'Crear nuevo plan', exact: true }).click();
  await page.getByLabel('Título del plan', { exact: true }).fill('Continuidad sintética');
  await page.getByRole('button', { name: 'Crear borrador', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Continuidad sintética', exact: true })).toBeVisible();
  const planId = new URL(page.url()).searchParams.get('plan');
  expect(planId).toBeTruthy();
  const composer = page.getByRole('form', { name: 'Procedimiento planificado' });
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('button', { name: /^Pieza 16:/ }).click();
  await composer.getByRole('textbox', { name: 'Sesiones (una por línea)', exact: true }).fill('Preparación\nColocación');
  await page.getByRole('button', { name: 'Diagnóstico', exact: true }).click();
  const guard = page.getByRole('dialog', { name: 'Cambios sin guardar' });
  await expect(guard).toBeVisible();
  await guard.getByRole('button', { name: 'Permanecer', exact: true }).click();
  await expect(composer.getByRole('textbox', { name: 'Sesiones (una por línea)', exact: true })).toHaveValue('Preparación\nColocación');
  await composer.getByRole('button', { name: 'Añadir procedimiento', exact: true }).click();
  const planChart = page.getByRole('region', { name: 'Odontograma del plan seleccionado', exact: true });
  await expect(planChart.locator('[data-arch-tooth="16"] text').filter({ hasText: /^P$/ })).toHaveCount(1);
  await expect(planChart.getByRole('button', { name: /^Pieza 17:/ })).not.toHaveAccessibleName(/Bracket/);
  await planChart.scrollIntoViewIfNeeded();
   await page.screenshot({ path: path.resolve(__dirname, `../../../openspec/changes/mirror-dental-diagnosis-workspace/evidence/${evidencePrefix}-selected-plan-1440.png`) });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Continuidad sintética', exact: true })).toBeVisible();
  expect(new URL(page.url()).searchParams.get('plan')).toBe(planId);
  await page.getByRole('button', { name: 'Diagnóstico', exact: true }).click();
  await expect(page.locator('[data-arch-tooth="16"] text').filter({ hasText: /^P$/ })).toHaveCount(0);
  await expect(page.getByRole('button', { name: /^Pieza 17:/ })).toHaveAccessibleName(/Bracket/);
  await page.getByRole('combobox', { name: 'Borrador para continuar', exact: true }).selectOption(planId!);
  await page.getByRole('button', { name: 'Continuar borrador', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Continuidad sintética', exact: true })).toBeVisible();
  expect((await (await page.request.get(`${base}/clinical-plans`)).json()).total).toBe(2);
  await page.getByRole('button', { name: 'Confirmar plan', exact: true }).click();
  await page.getByRole('dialog', { name: 'Confirmar plan', exact: true }).getByRole('button', { name: 'Confirmar plan', exact: true }).click();
  await page.getByRole('button', { name: 'Registrar aceptación', exact: true }).click();
  await page.getByRole('button', { name: 'Revisar acción', exact: true }).click();
  await page.getByRole('dialog', { name: 'Registrar aceptación', exact: true }).getByRole('button', { name: 'Registrar aceptación', exact: true }).click();
  const other = await context.newPage();
  await other.goto(page.url());
  await expect(other.getByText('En curso · Revisión 4', { exact: true })).toBeVisible();
  const complete = async (target: Page, text: string): Promise<void> => {
    await target.getByRole('button', { name: 'Completar siguiente sesión', exact: true }).click();
    await target.getByRole('textbox', { name: 'Nota clínica del procedimiento (opcional)', exact: true }).fill(text);
    await target.getByRole('button', { name: 'Revisar ejecución', exact: true }).click();
    await target.getByRole('dialog', { name: 'Completar sesión', exact: true }).getByRole('button', { name: 'Completar sesión', exact: true }).click();
  };
  await complete(page, 'Texto clínico privado sintético');
  await expect(page.getByText('1/2 sesiones completadas', { exact: true })).toBeVisible();
  await complete(other, 'Borrador segunda sesión');
  await other.getByRole('button', { name: 'Revisar versión guardada', exact: true }).click();
  await expect(other.getByRole('textbox', { name: 'Nota clínica del procedimiento (opcional)', exact: true })).toHaveValue('Borrador segunda sesión');
  await other.getByRole('button', { name: 'Revisar ejecución', exact: true }).click();
  await other.getByRole('dialog', { name: 'Completar sesión', exact: true }).getByRole('button', { name: 'Completar sesión', exact: true }).click();
  await expect(other.getByText('Completado · Revisión 6', { exact: true })).toBeVisible();
  await other.close();
  await page.reload();
  await expect(page.getByText('Completado · Revisión 6', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Actividad', exact: true }).click();
  const activityResponse = await page.request.get(`${base}/activity`);
  expect(activityResponse.status()).toBe(200);
  const activity = await activityResponse.json();
  expect(activity.total).toBe(14);
  expect(JSON.stringify(activity)).not.toMatch(/Texto clínico privado|Borrador segunda sesión/);
  const plannedTreatmentEvent = activity.items.find((event: { kind: string; href: string }) => event.kind === 'treatments' && event.href.includes(`plan=${planId}`));
  expect(plannedTreatmentEvent.href).toContain(`treatment=${plannedTreatmentEvent.resource_id}`);
  await page.getByRole('button', { name: 'Planes', exact: true }).click();
  await expect(page.getByText('7 eventos', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Sesión completada', exact: true }).first().click();
  await expect(page.getByText(/Revisión 6 · Completar sesión/)).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  const closeNavigation = page.getByRole('button', { name: 'Cerrar navegación', exact: true });
  if (await closeNavigation.isVisible()) await closeNavigation.click();
  await expect.poll(() => page.locator('.sidebar-container').evaluate((node) => node.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await page.getByText(/Revisión 6 · Completar sesión/).scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
   await page.screenshot({ path: path.resolve(__dirname, `../../../openspec/changes/mirror-dental-diagnosis-workspace/evidence/${evidencePrefix}-history-390.png`) });
  await page.goto(plannedTreatmentEvent.href);
  await expect(page.getByRole('heading', { name: 'Continuidad sintética', exact: true })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.activeElement?.textContent)).toContain('Bracket individual');
  await page.goto(`/patients/${patientId}?tab=activity`);
  await page.getByRole('link', { name: 'Nota clínica creada', exact: true }).first().click();
  await expect(page.getByRole('region', { name: 'Nota clínica seleccionada' })).toContainText('Revisión 1');
  await page.goto(`/patients/${patientId}?tab=clinical&clinical=diagnosis&treatment=${observed.id}`);
  await expect(page.getByRole('dialog', { name: /Editar procedimiento/ })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar procedimiento', exact: true }).click();
  await page.goto(`/patients/${secondId}?tab=clinical&clinical=planning&plan=${planId}`);
  await expect(page.getByText(/Plan no disponible/)).toBeVisible();
  await expect(page.getByRole('button', { name: 'Crear borrador', exact: true })).toHaveCount(0);
  await page.goto('/patients');
  await page.getByRole('textbox', { name: 'Buscar por nombre, teléfono o RUT', exact: true }).fill(patientLabel);
  await page.locator(`a[href="/patients/${patientId}"]`).click();
  await page.getByRole('tab', { name: 'Clínica', exact: true }).click();
  await page.getByRole('button', { name: 'Planificación', exact: true }).click();
  await page.getByRole('button', { name: 'Otro borrador · Borrador', exact: true }).click();
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('textbox', { name: 'Nota del procedimiento', exact: true }).fill('No trasladar');
  await page.goBack();
  await expect(guard).toBeVisible();
  await guard.getByRole('button', { name: 'Permanecer', exact: true }).click();
  expect(new URL(page.url()).searchParams.get('plan')).toBe(unusedId);
  await expect(composer.getByRole('textbox', { name: 'Nota del procedimiento', exact: true })).toHaveValue('No trasladar');
  await page.getByRole('link', { name: 'Pacientes', exact: true }).last().click();
  await expect(guard).toBeVisible();
  await guard.getByRole('button', { name: 'Permanecer', exact: true }).click();
  await expect(composer.getByRole('textbox', { name: 'Nota del procedimiento', exact: true })).toHaveValue('No trasladar');
  await page.getByRole('link', { name: 'Pacientes', exact: true }).last().click();
  await guard.getByRole('button', { name: 'Descartar y continuar', exact: true }).click();
  await expect(page).toHaveURL(/\/patients(?:\?|$)/);
  await page.goto(`/patients/${secondId}?tab=clinical&clinical=planning`);
  await expect(page.getByLabel('Título del plan', { exact: true })).toHaveValue('');
  expect(new URL(page.url()).searchParams.get('plan')).toBeNull();
  const foreign = await playwright.request.newContext({ baseURL: process.env.E2E_BASE_URL });
  expect((await foreign.post('/api/auth/login', { data: { email: process.env.E2E_FOREIGN_USER, password: process.env.E2E_FOREIGN_PASSWORD } })).status()).toBe(200);
  for (const resource of ['activity', `clinical-plans/${planId}`, `dental-treatments/${observed.id}`]) expect((await foreign.get(`${base}/${resource}`)).status()).toBe(404);
  await foreign.dispose();
  const persisted = await (await page.request.get(`${base}/clinical-plans/${planId}`)).json();
  expect(persisted.items[0].stages.map((stage: { status: string }) => stage.status)).toEqual(['completed', 'completed']);
  expect(persisted.items[0].treatment.state).toBe('performed');
  const evidence = JSON.stringify({ patientId, secondId, findingId: finding.id, observedId: observed.id, planId, unusedId, persisted, activity }, null, 2);
   await writeFile(path.resolve(__dirname, `../../../openspec/changes/mirror-dental-diagnosis-workspace/evidence/${evidencePrefix}-persisted.json`), evidence);
  await test.info().attach('slice8-persisted', { body: evidence, contentType: 'application/json' });
});

test('mirror slice10 preserves pre-mirror identities and one note composer across rail and Sheet', async ({ page }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8018' || !process.env.E2E_LEGACY_FIXTURE, 'Owned disposable legacy fixture only');
  const legacy = JSON.parse(await readFile(process.env.E2E_LEGACY_FIXTURE!, 'utf8')) as {
    patientId: string; findingId: string; originalId: string; replacementId: string; generalNoteId: string;
    snapshots: Record<string, unknown>;
  };
  expect((await page.request.post('/api/auth/login', { data: { email: 'slice10-owner@example.com', password: 'Synthetic-proof-10!' } })).status()).toBe(200);
  for (const [endpoint, snapshot] of Object.entries(legacy.snapshots)) {
    const response = await page.request.get(endpoint);
    expect(response.status()).toBe(200);
    expect(await response.json()).toEqual(snapshot);
  }
  const base = `/api/patients/${legacy.patientId}`;
  const diagnosis = `/patients/${legacy.patientId}?tab=clinical&clinical=diagnosis`;
  const linkedBody = `Contexto dental ${randomUUID().slice(0, 8)}`;
  expect((await page.request.post(`${base}/clinical-notes`, { data: {
    id: randomUUID(), operation_id: randomUUID(), expected_revision: 0,
    note_type: 'diagnosis', entity_kind: 'patient', entity_id: legacy.patientId,
    body: linkedBody, tooth_fdi: 18, dentition: 'permanent',
  } })).status()).toBe(201);
  await page.goto(`${diagnosis}&condition=${legacy.originalId}`);
  await expect(page.getByRole('button', { name: 'Temporal', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByText('Motivo de corrección: Corrección anterior al mirror', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Ver reemplazo vinculado', exact: true }).first().click();
  await expect(page).toHaveURL(new RegExp(`condition=${legacy.replacementId}`));
  await expect(page.getByRole('article', { name: /Pieza 52.*Caries.*Activa/ }).first()).toBeVisible();
  await page.goto(`${diagnosis}&condition=${legacy.findingId}`);
  await expect(page.getByRole('article', { name: /Pieza 16.*Fractura.*Activa/ })).toContainText('Revisión 2');
  await expect(page.getByRole('article', { name: /Pieza 16.*Fractura.*Activa/ }).getByText(/M, O/).first()).toBeVisible();
  await page.goto(`/patients/${legacy.patientId}?tab=info&note=${legacy.generalNoteId}`);
  await expect(page.getByText('Nota general conservada', { exact: true }).first()).toBeVisible();
  await page.goto(diagnosis);
  await page.setViewportSize({ width: 1600, height: 1000 });
  const general = page.getByRole('article', { name: 'Nota Administrativa', exact: true });
  await expect(general).toContainText('Nota general conservada');
  const writes: string[] = [];
  page.on('request', request => {
    if (request.url().includes(base) && ['POST', 'PATCH', 'DELETE'].includes(request.method())) writes.push(request.url());
  });
  const draftBody = `Borrador único ${randomUUID().slice(0, 8)}`;
  await page.getByLabel('Texto de nota clínica').fill(draftBody);
  const tooth16 = page.getByRole('button', { name: /^Pieza 16:/ });
  await tooth16.hover();
  await page.getByRole('checkbox', { name: 'Asociar al diente 16' }).uncheck();
  await general.hover();
  await expect(page.getByRole('checkbox', { name: 'Asociar al diente 16' })).not.toBeChecked();
  await page.getByRole('article', { name: 'Nota Diagnóstico', exact: true }).filter({ hasText: linkedBody }).hover();
  await expect(page.locator('[data-linked-highlight="18"]')).toHaveCount(1);
  await expect(page.getByRole('checkbox', { name: 'Asociar al diente 16' })).not.toBeChecked();
  await tooth16.hover();
  await expect(page.getByRole('checkbox', { name: 'Asociar al diente 16' })).not.toBeChecked();
  await page.getByRole('button', { name: /^Pieza 17:/ }).hover();
  await expect(page.getByRole('checkbox', { name: 'Asociar al diente 17' })).toBeChecked();
  await page.getByRole('article', { name: /Pieza 16.*Fractura.*Activa/ }).hover();
  await expect(page.locator('[data-linked-highlight="16"]')).toHaveCount(1);
  await expect(page.getByRole('checkbox', { name: 'Asociar al diente 17' })).toBeChecked();
  await tooth16.click();
  await expect(page.getByRole('dialog', { name: 'Pieza 16', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  expect(writes).toEqual([]);
  await page.setViewportSize({ width: 390, height: 844 });
  const closeNavigation = page.getByRole('button', { name: 'Cerrar navegación', exact: true });
  if (await closeNavigation.isVisible()) await closeNavigation.click();
  await page.getByRole('button', { name: 'Notas', exact: true }).click();
  await expect(page.getByLabel('Texto de nota clínica')).toHaveCount(1);
  await expect(page.getByLabel('Texto de nota clínica')).toHaveValue(draftBody);
  await expect(page.getByRole('checkbox', { name: 'Asociar al diente 16' })).toBeChecked();
  await page.getByRole('button', { name: 'Guardar', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Añadir nota', exact: true })).toBeVisible();
  expect(writes.filter(url => url.endsWith('/clinical-notes'))).toHaveLength(1);
  const notes = await (await page.request.get(`${base}/clinical-notes`)).json();
  const saved = notes.items.find((item: { body: string }) => item.body === draftBody);
  expect(saved.tooth_fdi).toBe(16);
  await page.reload();
  await page.getByRole('button', { name: 'Notas', exact: true }).click();
  await expect(page.getByRole('article', { name: 'Nota Diagnóstico', exact: true }).filter({ hasText: draftBody })).toContainText(draftBody);
  await page.screenshot({ path: path.resolve(__dirname, '../../../openspec/changes/mirror-dental-diagnosis-workspace/evidence/slice10-preserved-notes-390.png') });
  await test.info().attach('slice10-note', { body: JSON.stringify(saved), contentType: 'application/json' });
});

test('mirror slice10 rollback serves unchanged legacy HTTP snapshots', async ({ page }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8020' || !process.env.E2E_LEGACY_FIXTURE, 'Owned pre-mirror application rollback only');
  const legacy = JSON.parse(await readFile(process.env.E2E_LEGACY_FIXTURE!, 'utf8')) as { snapshots: Record<string, unknown> };
  expect((await page.request.post('/api/auth/login', { data: { email: 'slice10-owner@example.com', password: 'Synthetic-proof-10!' } })).status()).toBe(200);
  for (const [endpoint, snapshot] of Object.entries(legacy.snapshots)) {
    const response = await page.request.get(endpoint);
    expect(response.status()).toBe(200);
    expect(await response.json()).toEqual(snapshot);
  }
});
