import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';

test('mirror slice4 draft authoring, scope, replay, ordered sessions and reload', async ({ page }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8001', 'Isolated synthetic E2E only');
  const number = String(20000000 + Math.floor(Math.random() * 60000000));
  let sum = 0;
  for (let i = 0; i < number.length; i++) sum += Number(number[number.length - 1 - i]) * (2 + i % 6);
  const check = 11 - sum % 11;
  const response = await page.request.post('/api/patients', { data: { first_name: 'Sintética', last_name: `Planes ${randomUUID().slice(0, 8)}`, rut: `${number}-${check === 11 ? '0' : check === 10 ? 'K' : check}` } });
  expect(response.status()).toBe(201);
  const patientId = (await response.json()).id;
  const base = `/api/patients/${patientId}/clinical-plans`;
  await page.goto(`/patients/${patientId}?tab=clinical&clinical=planning`);
  await expect(page.getByText('Cargando planes', { exact: true })).toBeHidden();
  await page.getByLabel('Título del plan', { exact: true }).fill('Plan sintético');
  await page.getByRole('button', { name: 'Crear borrador', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plan sintético', exact: true })).toBeVisible();
  const composer = page.getByRole('form', { name: 'Procedimiento planificado', exact: true });
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('button', { name: /^Pieza 16:/ }).click();
  await composer.getByRole('textbox', { name: 'Sesiones (una por línea)', exact: true }).fill('Preparación\nColocación');
  await page.getByRole('button', { name: 'Diagnóstico', exact: true }).click();
  const guard = page.getByRole('dialog', { name: 'Cambios sin guardar', exact: true });
  await expect(guard).toBeVisible();
  await guard.getByRole('button', { name: 'Permanecer', exact: true }).click();
  let original: unknown;
  await page.route('**/clinical-plans/*/items', async route => {
    original = route.request().postDataJSON();
    await route.fetch(); await route.abort();
  }, { times: 1 });
  await composer.getByRole('button', { name: 'Añadir procedimiento', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reintentar misma operación', exact: true })).toBeVisible();
  const retry = page.waitForRequest(request => request.method() === 'POST' && request.url().endsWith('/items'));
  await page.getByRole('button', { name: 'Reintentar misma operación', exact: true }).click();
  expect((await retry).postDataJSON()).toEqual(original);
  await expect(page.getByText('1. Bracket individual (reposición)', { exact: true })).toBeVisible();
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('REST-BRIDGE-ZIR');
  for (const tooth of [14, 15, 16]) await composer.getByRole('button', { name: new RegExp(`^Pieza ${tooth}:`) }).click();
  await composer.getByRole('group', { name: 'Pieza 15', exact: true }).getByRole('combobox', { name: 'Rol', exact: true }).selectOption('pontic');
  await composer.getByRole('button', { name: 'Añadir procedimiento', exact: true }).click();
  await expect(page.getByText('2. Puente zirconio', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Subir procedimiento 2', exact: true }).click();
  await expect(page.getByText('1. Puente zirconio', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Editar sesión 1', exact: true }).last().click();
  await page.getByRole('textbox', { name: 'Nombre de sesión', exact: true }).fill('Preparación revisada');
  await page.getByRole('button', { name: 'Guardar sesión', exact: true }).click();
  await expect(page.getByText('1. Preparación revisada · Pendiente', { exact: true })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('slice4-draft-desktop.png') });
  const plans = (await (await page.request.get(base)).json()).items;
  expect(plans).toHaveLength(1);
  expect(plans[0].items.map((item: { treatment: { variant_id: string } }) => item.treatment.variant_id)).toEqual(['REST-BRIDGE-ZIR', 'ORTO-BRACK']);
  expect((await (await page.request.get(`/api/patients/${patientId}/dental-treatments`)).json()).total).toBe(0);
  await page.reload();
  await page.getByRole('button', { name: 'Plan sintético · Borrador', exact: true }).click();
  await expect(page.getByText('1. Puente zirconio', { exact: true })).toBeVisible();
  await expect(page.getByText('1. Preparación revisada · Pendiente', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const closeNavigation = page.getByRole('button', { name: 'Cerrar navegación', exact: true });
  if (await closeNavigation.isVisible()) await closeNavigation.click();
  await expect.poll(() => page.locator('.sidebar-container').evaluate((node) => node.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await page.getByText('1. Puente zirconio', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath('slice4-draft-narrow.png') });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('button', { name: /^Seleccionar pieza 17:/ }).click();
  await page.getByRole('tab', { name: 'Información', exact: true }).click();
  await guard.getByRole('button', { name: 'Guardar y continuar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Notas generales', exact: true })).toBeVisible();
  const savedOnLeave = (await (await page.request.get(`${base}/${plans[0].id}`)).json());
  expect(savedOnLeave.items).toHaveLength(3);
  expect(savedOnLeave.items[2].treatment.teeth[0].tooth_fdi).toBe(17);
  await test.info().attach('slice4-persisted', { body: JSON.stringify({ patientId, plan: plans[0] }), contentType: 'application/json' });
});

test('mirror slice5 explicit confirmation, acceptance, closure, reactivation and history', async ({ page }) => {
  test.skip(process.env.E2E_BASE_URL !== 'http://localhost:8001', 'Isolated synthetic E2E only');
  const number = String(20000000 + Math.floor(Math.random() * 60000000));
  let sum = 0;
  for (let i = 0; i < number.length; i++) sum += Number(number[number.length - 1 - i]) * (2 + i % 6);
  const check = 11 - sum % 11;
  const response = await page.request.post('/api/patients', { data: { first_name: 'Sintética', last_name: `Ciclo ${randomUUID().slice(0, 8)}`, rut: `${number}-${check === 11 ? '0' : check === 10 ? 'K' : check}` } });
  expect(response.status()).toBe(201);
  const patientId = (await response.json()).id;
  const base = `/api/patients/${patientId}/clinical-plans`;
  await page.goto(`/patients/${patientId}?tab=clinical&clinical=planning`);
  await page.getByRole('textbox', { name: 'Título del plan', exact: true }).fill('Ciclo clínico sintético');
  await page.getByRole('button', { name: 'Crear borrador', exact: true }).click();
  const composer = page.getByRole('form', { name: 'Procedimiento planificado', exact: true });
  await composer.getByRole('combobox', { name: 'Procedimiento', exact: true }).selectOption('ORTO-BRACK');
  await composer.getByRole('button', { name: /^Pieza 16:/ }).click();
  await composer.getByRole('button', { name: 'Añadir procedimiento', exact: true }).click();
  await expect(page.getByText('Borrador · Revisión 2', { exact: true })).toBeVisible();
  const confirmAction = async (label: string): Promise<void> => {
    await page.getByRole('button', { name: label, exact: true }).click();
    await page.getByRole('dialog', { name: label, exact: true }).getByRole('button', { name: label, exact: true }).click();
  };
  await confirmAction('Confirmar plan');
  await expect(page.getByText('Pendiente de aceptación · Revisión 3', { exact: true })).toBeVisible();
  await confirmAction('Reabrir plan');
  await expect(page.getByText('Borrador · Revisión 4', { exact: true })).toBeVisible();
  await confirmAction('Confirmar plan');
  await page.getByRole('button', { name: 'Registrar aceptación', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nota de aceptación (opcional)', exact: true }).fill('Aceptación clínica sintética');
  await page.getByRole('button', { name: 'Revisar acción', exact: true }).click();
  const acceptance = page.getByRole('dialog', { name: 'Registrar aceptación', exact: true });
  await expect(acceptance.getByText(/No representa una firma/)).toBeVisible();
  let original: unknown;
  await page.route('**/clinical-plans/*/accept', async route => { original = route.request().postDataJSON(); await route.fetch(); await route.abort(); }, { times: 1 });
  await acceptance.getByRole('button', { name: 'Registrar aceptación', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reintentar misma operación', exact: true })).toBeVisible();
  const retry = page.waitForRequest(request => request.method() === 'POST' && request.url().endsWith('/accept'));
  await page.getByRole('button', { name: 'Reintentar misma operación', exact: true }).click();
  expect((await retry).postDataJSON()).toEqual(original);
  await expect(page.getByText('En curso · Revisión 6', { exact: true })).toBeVisible();
  await expect(page.getByText(/Aceptación registrada/)).toContainText('Aceptación clínica sintética');
  await page.screenshot({ path: test.info().outputPath('slice5-accepted-desktop.png') });
  await page.getByRole('button', { name: 'Cerrar plan', exact: true }).click();
  await page.getByRole('combobox', { name: 'Motivo del cierre', exact: true }).selectOption('expired');
  await page.getByRole('textbox', { name: 'Nota del cierre (opcional)', exact: true }).fill('Cierre sintético');
  await page.getByRole('button', { name: 'Revisar acción', exact: true }).click();
  await page.getByRole('dialog', { name: 'Cerrar plan', exact: true }).getByRole('button', { name: 'Cerrar plan', exact: true }).click();
  await expect(page.getByText('Cerrado · Revisión 7', { exact: true })).toBeVisible();
  await expect(page.getByText('Plan de solo lectura. Su historial se conserva.', { exact: true })).toBeVisible();
  await expect(composer).toBeHidden();
  const closed = (await (await page.request.get(base)).json()).items[0];
  expect(closed.closure_reason).toBe('expired');
  expect(closed.accepted_at).toBeTruthy();
  const denied = await page.request.patch(`${base}/${closed.id}`, { data: { operation_id: randomUUID(), expected_revision: 7, title: 'Forbidden' } });
  expect(denied.status()).toBe(409);
  await page.reload();
  await page.getByRole('button', { name: 'Ciclo clínico sintético · Cerrado', exact: true }).click();
  await expect(page.getByText('Cerrado · Revisión 7', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const closeNavigation = page.getByRole('button', { name: 'Cerrar navegación', exact: true });
  if (await closeNavigation.isVisible()) await closeNavigation.click();
  await expect.poll(() => page.locator('.sidebar-container').evaluate((node) => node.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await page.getByRole('button', { name: 'Reactivar plan', exact: true }).click();
  const reactivation = page.getByRole('dialog', { name: 'Reactivar plan', exact: true });
  await page.screenshot({ path: test.info().outputPath('slice5-reactivation-narrow.png') });
  await reactivation.getByRole('button', { name: 'Reactivar plan', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByText('Borrador · Revisión 8', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Historial del plan', exact: true }).click();
  await expect(page.getByText(/Revisión 7 · Cerrar plan/)).toBeVisible();
  const history = (await (await page.request.get(`${base}/${closed.id}/revisions`)).json()).items;
  expect(history.find((revision: { revision: number }) => revision.revision === 7).after.closure_reason).toBe('expired');
  expect(history.find((revision: { revision: number }) => revision.revision === 6).after.acceptance_note).toBe('Aceptación clínica sintética');
  await test.info().attach('slice5-persisted', { body: JSON.stringify({ patientId, planId: closed.id, closedRevision: closed.revision, history }), contentType: 'application/json' });
});
